apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bubble-animation-app  #argocd app name
  namespace: openshift-gitops #managed by argoCD extension
spec:
  destination:
    namespace: bubble-animation #projectname
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: bubble-animation/application-mainfest
    repoURL: https://github.com/openshift-demo/
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true