apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: nodejs-app
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: lab03-build-pipeline-from-git/manifest
    repoURL: https://github.com/dungphamdev/openshift-demo/