apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-image
spec:
  workspaces:
    - name: source-workspace
      mountPath: /workspace/source
  steps:
    - name: build-docker-image
      image: gcr.io/kaniko-project/executor:v1.7.0
      workingDir: /workspace/source
      env:
        - name: DOCKER_CONFIG
          value: /workspace/source/.docker
      script: |
         /kaniko/executor --context=/workspace/source --dockerfile=/workspace/source/Dockerfile --destination=image-registry.openshift-image-registry.svc:5000/tommy/nodejs-app-image:latest
