apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-image
spec:
  workspaces:
    - name: source-workspace
      mountPath: /workspace/source
  steps:
    - name: build-docker-image
      image: docker:latest
      workingDir: /workspace/source
      script: |
        ls -al
        docker build -t image-registry.openshift-image-registry.svc:5000/tommy/nodejs-app-image:latest .



