apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-image
spec:
  securityContext:
    runAsUser: 0  # Run as root
  workspaces:
    - name: source-workspace
      mountPath: /workspace/source
  steps:
    - name: build-docker-image
      image: quay.io/buildah/stable:latest
      workingDir: /workspace/source
      script: |
        ls -al
        buildah --version
        buildah bud -t image-registry.openshift-image-registry.svc:5000/tommy/nodejs-app-image:latest .



