apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah-task
spec:
  workspaces:
    - name: source-workspace
      mountPath: /workspace/source
  steps:
    - name: build-image
      image: quay.io/buildah/stable
      workingDir: /workspace/source
      securityContext:
        capabilities:
          add:
            - "SETFCAP"
            - "SYS_ADMIN"
            - "MKNOD"
            - "SYS_CHROOT"
            - "SETFCAP"

      script: |
        ls
        whoami
        id
        getent group
        buildah bud -t test:latest .