apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah-task
spec:
  workspaces:
    - name: source-workspace
      mountPath: /workspace/source
  steps:
    - name: build-image
      image: quay.io/buildah/stable
      workingDir: /workspace/source
      securityContext:
        capabilities:
          add:
            - "SETFCAP"

      script: |
        yum install fuse
        modprobe fuse
        buildah bud -t test:latest .