apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: fetch-repo
spec:
  steps:
    - name: git-source
      image: alpine/git
      workingDir: /workspace/source
      script: |
        git clone $(ConfigMap.git-config-nodejs-app.url) .
        git checkout $(ConfigMap.git-config-nodejs-app.revision)