apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: fetch-repo
spec:
  workspaces:
    - name: source-workspace
      mountPath: /workspace/source
  steps:
    - name: git-source
      image: alpine/git
      workingDir: /workspace/source
      env:
        - name: REPO_URL
          valueFrom:
            configMapKeyRef:
              name: git-config-nodejs-app
              key: url
        - name: REVISION
          valueFrom:
            configMapKeyRef:
              name: git-config-nodejs-app
              key: revision
      script: |
        git clone $REPO_URL .
        git config --global --add safe.directory /workspace/source
        git checkout $REVISION
        ls -al