apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: fetch-repo
spec:
  steps:
    - name: git-source
      image: alpine/git
      workingDir: /workspace/source
      env:
        - name: REPO_URL
          valueFrom:
            configMapKeyRef:
              name: git-config-nodejs-app
              key: url
        - name: REVISION
          valueFrom:
            configMapKeyRef:
              name: git-config-nodejs-app
              key: revision
      script: |
        git clone $REPO_URL .
        git checkout $REVISION