apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: simple-nodesj-hello-world-pipeline
spec:
  tasks:
    - name: fetch-source-task
      taskRef:
        name: fetch-repo
      workspaces:
        - name: shared-workspace
    - name: build-image
      taskRef: 
        name: build-image
      runAfter:
        - fetch-source-task
      workspaces:
        - name: shared-workspace

