apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: simple-nodesj-hello-world-pipeline
spec:
  workspaces:
    - name: shared-workspace
    #TODO: define workspace volume type so the pipeline can run with no params
     
  tasks:
    - name: fetch-source-task
      taskRef:
        name: fetch-repo
      workspaces:
        - name: source-workspace
          workspace: shared-workspace

    - name: build-image-task
      taskRef:
        name: buildah-task
      runAfter:
        - fetch-source-task
      workspaces:
        - name: source-workspace
          workspace: shared-workspace