apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: simple-nodesj-hello-world-pipeline
spec:
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        metadata:
          name: shared-pvc
        spec:
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 1Gi
  tasks:
    - name: fetch-source-task
      taskRef:
        name: fetch-repo
      workspaces:
        - name: source-workspace
          workspace: shared-workspace
    - name: build-image
      taskRef: 
        name: build-image
      runAfter:
        - fetch-source-task
      workspaces:
        - name: source-workspace
          workspace: shared-workspace

