apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: simple-nodesj-hello-world-pipeline
spec:
  tasks:
    - name: fetch-source-task
      taskRef:
        name: fetch-repo
    - name: build-image
      taskRef: 
        name: build-image
